#!/usr/bin/env bash
# Monad + biyachain 乐观执行联调脚本
#
# 用法:
#   ./test.sh init        # 或 ./test.sh 1 — 清理环境并初始化
#   ./test.sh biyachaind  # 或 ./test.sh 2 — 前台运行 biyachaind（日志直出终端）
#   ./test.sh monad       # 或 ./test.sh 3 — 前台运行 monad-node（终端 + .monad-home/monad-node.log）
#   ./test.sh sendtx      # 或 ./test.sh 4 — 构造 bank send 并 feed 到 monad mempool
#
# 典型流程: ./test.sh init → 终端 A: ./test.sh biyachaind → 终端 B: ./test.sh monad → 终端 C: ./test.sh sendtx
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$SCRIPT_DIR"
ENV_FILE="${REPO}/.monad-dev.env"

BIYACHAIND_BIN="${BIYACHAIND_BIN:-${REPO}/biyachain-core/biyachaind}"
BIYAHOME="${BIYAHOME:-${REPO}/.biyachaind}"
MONAD_RUN_DIR="${MONAD_RUN_DIR:-${REPO}/.monad-home}"
MONAD_LOG_FILE="${MONAD_LOG_FILE:-${MONAD_RUN_DIR}/monad-node.log}"
MONAD_ABCI_SOCKET="${MONAD_ABCI_SOCKET:-unix:///tmp/biyachain-abci-fresh.sock}"

usage() {
  cat <<EOF
用法: $0 <command>

  init        | 1   清理旧进程/目录/socket，初始化 biyachain 与 monad 运行目录
  biyachaind  | 2   启动 biyachaind（前台，日志实时打印到当前终端）
  monad       | 3   启动 monad-node（前台，终端 + 日志文件 tee）
  sendtx      | 4   构造 bank send 交易并 feed 到 monad mempool（需 2/3 已运行）

环境文件: ${ENV_FILE}（由 init 写入，biyachaind/monad 会自动 source）

可覆盖变量: BIYAHOME, MONAD_RUN_DIR, MONAD_LOG_FILE, MONAD_ABCI_SOCKET, BIYACHAIND_BIN
EOF
}

die() {
  echo "error: $*" >&2
  exit 1
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by test.sh init — do not edit paths unless you know what you are doing
export REPO="${REPO}"
export BIYACHAIND_BIN="${BIYACHAIND_BIN}"
export BIYAHOME="${BIYAHOME}"
export MONAD_RUN_DIR="${MONAD_RUN_DIR}"
export MONAD_LOG_FILE="${MONAD_LOG_FILE}"
export MONAD_ABCI_SOCKET="${MONAD_ABCI_SOCKET}"
export MONAD_ABCI_ENDPOINT="${MONAD_ABCI_SOCKET}"
export MONAD_COSMOS_GENESIS_PATH="${BIYAHOME}/config/genesis.json"
export MONAD_MEMPOOL_SOCK="${MONAD_RUN_DIR}/mempool.sock"
export MONAD_COSMOS_LEDGER_DRIVEN=true
export RUST_LOG="${RUST_LOG:-info}"
export GRPC_ADDR="127.0.0.1:9900"
EOF
}

load_env() {
  [[ -f "$ENV_FILE" ]] || die "未找到 ${ENV_FILE}，请先运行: $0 init"
  # shellcheck source=/dev/null
  source "$ENV_FILE"
}

cmd_init() {
  echo "==> 停止旧进程"
  pkill -9 -f 'monad-node' 2>/dev/null || true
  pkill -9 -f 'biyachaind start' 2>/dev/null || true
  sleep 0.5

  echo "==> 清理 socket / 运行目录 / 环境文件"
  rm -f /tmp/biyachain-abci.sock /tmp/biyachain-abci-fresh.sock
  rm -rf "$BIYAHOME" "$MONAD_RUN_DIR"
  rm -f "$ENV_FILE"

  [[ -x "$BIYACHAIND_BIN" ]] || die "未找到可执行文件: $BIYACHAIND_BIN（请先 go build ./cmd/biyachaind）"

  echo "==> 初始化 biyachain home: $BIYAHOME"
  export BIYAHOME BIYACHAIND_BIN
  "${REPO}/biyachain-core/scripts/init-standalone-abci.sh"

  echo "==> 创建测试收款密钥 recipient"
  "${BIYACHAIND_BIN}" keys add recipient \
    --home "$BIYAHOME" \
    --keyring-backend test

  echo "==> 准备 monad 运行目录: $MONAD_RUN_DIR"
  mkdir -p "$MONAD_RUN_DIR/ledger/headers" "$MONAD_RUN_DIR/ledger/bodies" "$MONAD_RUN_DIR/ledger/cosmos-commits"
  cp "${REPO}/docker/devnet/monad/config/forkpoint.genesis.toml" "$MONAD_RUN_DIR/forkpoint.toml"
  cp "${REPO}/docker/devnet/monad/config/validators.toml" "$MONAD_RUN_DIR/validators.toml"

  write_env_file

  echo ""
  echo "初始化完成。"
  echo "  BIYAHOME=$BIYAHOME"
  echo "  MONAD_RUN_DIR=$MONAD_RUN_DIR"
  echo "  MONAD_LOG_FILE=$MONAD_LOG_FILE"
  echo "  MONAD_ABCI_SOCKET=$MONAD_ABCI_SOCKET"
  echo "  环境已写入: $ENV_FILE"
  echo ""
  echo "下一步:"
  echo "  终端 A: $0 biyachaind"
  echo "  终端 B: $0 monad"
  echo "  终端 C: $0 sendtx"
}

cmd_biyachaind() {
  load_env
  [[ -d "$BIYAHOME" ]] || die "BIYAHOME 不存在，请先: $0 init"
  [[ -x "$BIYACHAIND_BIN" ]] || die "未找到: $BIYACHAIND_BIN"

  rm -f /tmp/biyachain-abci-fresh.sock

  echo "==> 启动 biyachaind（Ctrl+C 停止）"
  echo "    home=$BIYAHOME"
  echo "    abci=$MONAD_ABCI_SOCKET"
  echo "    ledger=$MONAD_RUN_DIR/ledger"
  echo ""

  exec "$BIYACHAIND_BIN" start \
    --home "$BIYAHOME" \
    --with-comet=false \
    --transport socket \
    --address "$MONAD_ABCI_SOCKET" \
    --grpc.enable=true \
    --grpc.address=0.0.0.0:9900 \
    --json-rpc.enable=false \
    --minimum-gas-prices 1byb \
    --optimistic-execution-enabled=true \
    --monad-ledger-path="$MONAD_RUN_DIR/ledger" \
    --log-level info
}

cmd_monad() {
  load_env
  [[ -d "$MONAD_RUN_DIR" ]] || die "MONAD_RUN_DIR 不存在，请先: $0 init"
  [[ -f "$MONAD_COSMOS_GENESIS_PATH" ]] || die "genesis 不存在: $MONAD_COSMOS_GENESIS_PATH"

  sock_path="${MONAD_ABCI_SOCKET#unix://}"
  if [[ ! -S "$sock_path" ]]; then
    die "ABCI socket 不存在 ($sock_path)，请先在另一终端运行: $0 biyachaind"
  fi

  cd "$REPO"

  mkdir -p "$(dirname "$MONAD_LOG_FILE")"
  : >"$MONAD_LOG_FILE"

  echo "==> 启动 monad-node（Ctrl+C 停止）"
  echo "    MONAD_ABCI_ENDPOINT=$MONAD_ABCI_ENDPOINT"
  echo "    MONAD_COSMOS_GENESIS_PATH=$MONAD_COSMOS_GENESIS_PATH"
  echo "    ledger=$MONAD_RUN_DIR/ledger"
  echo "    log=$MONAD_LOG_FILE"
  echo ""

  export MONAD_COSMOS_LEDGER_DRIVEN=true
  sudo sysctl -w vm.nr_hugepages=2048
  # UDP buffer sizes
  sudo sysctl -w net.core.rmem_max=62500000
  sudo sysctl -w net.core.rmem_default=62500000
  sudo sysctl -w net.core.wmem_max=62500000
  sudo sysctl -w net.core.wmem_default=62500000
  # TCP buffer sizes
  sudo sysctl -w net.ipv4.tcp_rmem='4096 12582912 12582912'
  sudo sysctl -w net.ipv4.tcp_wmem='4096 12582912 12582912'

  cargo run -p monad-node --bin monad-node -- \
    --secp-identity "${REPO}/docker/devnet/monad/config/id-secp" \
    --bls-identity "${REPO}/docker/devnet/monad/config/id-bls" \
    --node-config "${REPO}/docker/devnet/monad/config/node.toml" \
    --forkpoint-config "$MONAD_RUN_DIR/forkpoint.toml" \
    --validators-path "$MONAD_RUN_DIR/validators.toml" \
    --wal-path "$MONAD_RUN_DIR/wal" \
    --mempool-ipc-path "$MONAD_RUN_DIR/mempool.sock" \
    --control-panel-ipc-path "$MONAD_RUN_DIR/controlpanel.sock" \
    --ledger-path "$MONAD_RUN_DIR/ledger" \
    --statesync-ipc-path "$MONAD_RUN_DIR/statesync.sock" \
    --triedb-path "$MONAD_RUN_DIR" \
    --persisted-peers-path "$MONAD_RUN_DIR/peers.json" \
    2>&1 | tee "$MONAD_LOG_FILE"
}

cmd_sendtx() {
  load_env
  [[ -d "$BIYAHOME" ]] || die "BIYAHOME 不存在，请先: $0 init"
  [[ -x "$BIYACHAIND_BIN" ]] || die "未找到: $BIYACHAIND_BIN"
  [[ -f "${REPO}/scripts/cosmos_monad_genesis_tx_example.sh" ]] \
    || die "未找到 scripts/cosmos_monad_genesis_tx_example.sh"

  if [[ ! -S /tmp/biyachain-abci-fresh.sock ]]; then
    die "ABCI socket 不存在，请先在另一终端运行: $0 biyachaind"
  fi
  if [[ ! -S "$MONAD_MEMPOOL_SOCK" ]]; then
    die "mempool socket 不存在，请先在另一终端运行: $0 monad ($MONAD_MEMPOOL_SOCK)"
  fi
  if ! "${BIYACHAIND_BIN}" keys show recipient \
    --home "$BIYAHOME" --keyring-backend test &>/dev/null; then
    die "keyring 缺少 recipient，请重新: $0 init"
  fi

  export BIYAHOME BIYACHAIND_BIN MONAD_MEMPOOL_SOCK MONAD_COSMOS_GENESIS_PATH GRPC_ADDR
  local tx_script="${REPO}/scripts/cosmos_monad_genesis_tx_example.sh"
  local raw="${BIYAHOME}/monad-tx-out/tx.raw"

  echo "==> 发送前余额 / sequence"
  bash "$tx_script" query || true

  echo ""
  echo "==> 构造并签名 bank send（validator -> recipient）"
  bash "$tx_script" transfer

  [[ -f "$raw" ]] || die "未生成 tx.raw: $raw"

  echo ""
  echo "==> feed 到 monad mempool: $MONAD_MEMPOOL_SOCK"
  cd "$REPO"
  cargo run -q -p monad-txpool --bin cosmos-txpool-feed -- "$MONAD_MEMPOOL_SOCK" "$raw"

  echo ""
  echo "==> 等待出块后查询（约 3s）"
  sleep 3
  bash "$tx_script" query || true
  echo ""
  echo "若余额 / from_sequence 未变，请检查 monad / biyachaind 日志，或运行: bash $tx_script diagnose"
}

main() {
  local cmd="${1:-}"
  case "$cmd" in
    init | 1) cmd_init ;;
    biyachaind | 2) cmd_biyachaind ;;
    monad | 3) cmd_monad ;;
    sendtx | 4) cmd_sendtx ;;
    -h | --help | help | "") usage; [[ -n "$cmd" ]] || exit 0 ;;
    *) die "未知命令: $cmd（运行 $0 --help 查看用法）" ;;
  esac
}

main "$@"
