{
 "title": "Block Performance 统计",
 "tags": [
  "monad",
  "loki",
  "block-performance"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SERVICE",
    "label": "Monad Service",
    "query": "monad-a,monad-b,monad-c,monad-d"
   },
   { "name": "DS_LOKI", "label": "Loki Datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "区块数量（观测窗口）",
   "type": "stat",
   "description": "观测窗口内的出块数量",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=consensus\" [$__range])",
     "legendFormat": "区块数"
    }
   ]
  },
  {
   "title": "平均出块时间",
   "type": "stat",
   "description": "平均出块时间 = avg_over_time(total [$__range])，窗口内所有区块总耗时的平均值，单位 ms",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by () (avg_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=consensus\" | logfmt | unwrap total | __error__=\"\" [$__range]))",
     "legendFormat": "均值"
    }
   ]
  },
  {
   "title": "总交易数（观测窗口）",
   "type": "stat",
   "description": "观测窗口内打包的总交易数",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (sum_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=txs\" | logfmt | unwrap txs | __error__=\"\" [$__range]))",
     "legendFormat": "总交易数"
    }
   ]
  },
  {
   "title": "TPS（总交易数÷窗口秒数）",
   "type": "stat",
   "description": "sum(txs in range) / $__range_s，反映观测窗口内的平均 TPS",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (sum_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=txs\" | logfmt | unwrap txs | __error__=\"\" [$__range])) / $__range_s",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "共识阶段耗时趋势",
   "type": "timeseries",
   "description": "共识各阶段每块耗时（Loki），同时展示总出块时间与各阶段耗时",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by () (avg_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=consensus\" | logfmt | unwrap total | __error__=\"\" [$__interval]))",
     "legendFormat": "出块时间"
    },
    {
     "expr": "avg by () (avg_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=consensus\" | logfmt | unwrap new_height | __error__=\"\" [$__interval]))",
     "legendFormat": "[1] NewHeight"
    },
    {
     "expr": "avg by () (avg_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=consensus\" | logfmt | unwrap new_round | __error__=\"\" [$__interval]))",
     "legendFormat": "[2] NewRound"
    },
    {
     "expr": "avg by () (avg_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=consensus\" | logfmt | unwrap propose | __error__=\"\" [$__interval]))",
     "legendFormat": "[3] Propose"
    },
    {
     "expr": "avg by () (avg_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=consensus\" | logfmt | unwrap prevote | __error__=\"\" [$__interval]))",
     "legendFormat": "[4] Prevote"
    },
    {
     "expr": "avg by () (avg_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=consensus\" | logfmt | unwrap precommit | __error__=\"\" [$__interval]))",
     "legendFormat": "[5] Precommit"
    },
    {
     "expr": "avg by () (avg_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=consensus\" | logfmt | unwrap commit | __error__=\"\" [$__interval]))",
     "legendFormat": "[6] Commit"
    }
   ]
  },
  {
   "title": "平均每块交易数",
   "type": "stat",
   "description": "平均每块交易数 = avg_over_time(txs [$__range])，窗口内每个区块 txs 的平均值，等价于总交易数 ÷ 总块数",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by () (avg_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=txs\" | logfmt | unwrap txs | __error__=\"\" [$__range]))",
     "legendFormat": "均值"
    }
   ]
  },
  {
   "title": "区块交易数",
   "type": "timeseries",
   "description": "每个点表示 $__interval 窗口内各区块 txs 的平均值，用于观察每块交易数随时间的变化趋势",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by () (avg_over_time({job=\"monad-docker\", service=~\"$SERVICE\"} |= \"msg=txs\" | logfmt | unwrap txs | __error__=\"\" [$__interval]))",
     "legendFormat": "交易数"
    }
   ]
  }
 ]
}